### ISSUE TITLE
FR: preserve RFC1918 subnets

### ISSUE THREAD

**Issue by dhalperi** [intentionet/netconan#111]
* 10.0.0.0/8 IP addresses: 10.0.0.0 -- 10.255.255.255
* 172.16.0.0/12 IP addresses: 172.16.0.0 -- 172.31.255.255
* 192.168.0.0/16 IP addresses: 192.168.0.0 – 192.168.255.255

Would be nice if Netconan kept these subnets intact too.

**Comment by sfraint** [comment]
Fixed in https://github.com/intentionet/netconan/pull/112 (these prefixes are preserved but host bits are still anonymized)
