### ISSUE TITLE
FortiOS SNMP Community Removal

### ISSUE THREAD

**Issue by ryanmerolle** [intentionet/netconan#155]
SNMP Communities are not removed from FortiOS devices:

```
config system snmp community
    edit 100
        set name "communityXYZ"
    next
end
```

**Comment by dhalperi** [comment]
Netconan line-by-line and is oblivious to the type of file it's anonymizing or the multi-line structures therein.

I don't see how we can possibly catch this case -- `set name "foo"` is too generic. It's used for naming all kinds of things in FortiOS configs.

The best way to handle this is probably to add your secrets of this type to the list of reserved words. Then they will be one-way hashed.
