### ISSUE TITLE
-d argument does not seem to work

### ISSUE THREAD

**Issue by Yoo33** [intentionet/netconan#164]
Hi,

am I the only one having trouble with the -d args ?
The dump file is created but it is always empty.

Awesome tool beside that :)

**Comment by sfraint** [comment]
Hey @Yoo33 ! It is not just you, `-d` is busted, and thanks for filing the issue!

In the meantime, what are you trying to accomplish with the dumped map? If you just want to determine the original addresses from an anonymized file, you can try the `--undo` option (with the same `--salt` from the original anonymization).

**Comment by Yoo33** [comment]
Hi sfraint, sorry for the late answer and thanks for the quick fix ! 
As a workaround I was using grep with the debug option on

I just tested the new master and it is working fine.

Thanks again, I am going to anonymise every single file I find from now on.
