### ISSUE TITLE
Support IOS-XR named community sets as a reserved word during anonymization

### ISSUE THREAD

**Issue by saparikh** [intentionet/netconan#72]
IOS-XR BGP policy allows you to set a BGP community by either:
    a) directly referencing the target community in the config
         `set community 65001:1111`
    b) referencing a community-set in the config
         ` community-set BAR`
         `     65001:1111`
         ` set community BAR`

A sample configuration snippet for community-sets and use in a BGP policy is shown below:

```
community-set LOCAL-NOPREPEND
  1111:2222
end-set
!
community-set LOCAL-LASTRESORT
  1111:4444
end-set
!
community-set LOCAL-HIGHLOCPREF
  1111:1111
end-set
!
!
route-policy FOO
  if destination in BAR or destination in BAZ then
    set community LOCAL-NOPREPEND
    if destination in FOOBAR then
      set community LOCAL-LASTRESORT
    endif
    if destination in BAZBAR then
      set community LOCAL-HIGHLOCPREF
      set community LOCAL-LASTRESORT
    else
      set community LOCAL-NOPREPEND
      set community LOCAL-LASTRESORT
    endif
  else
    drop
  endif
end-policy
```
Netconan will turn that config into:

```
community-set LOCAL-NOPREPEND
  1111:2222
end-set
!
community-set LOCAL-LASTRESORT
  1111:4444
end-set
!
community-set LOCAL-HIGHLOCPREF
  1111:1111
end-set
!
!
route-policy FOO
  if destination in BAR or destination in BAZ then
    set community netconanRemoved42
    if destination in FOOBAR then
      set community netconanRemoved19
    endif
    if destination in BAZBAR then
      set community netconanRemoved20
      set community netconanRemoved21
    else
      set community netconanRemoved22
      set community netconanRemoved23
    endif
  else
    drop
  endif
end-policy
```

**Comment by ratulm** [comment]
This one is tricky. As a workaround, a flag that lets users pick which semantics they want for `set community`?

**Comment by dhalperi** [comment]
(mirroring some verbal discussion into the issue)

Personally, I don't think that kind of feature creep is worth it (a detailed hack for this specific instance of ambiguous grammar); Netconan is always going to be best-effort and simplicity is a real virtue.

We already have functionality for reserved words based on the unified list of tokens from Batfish grammars. Maybe we make the reserved words easily user-extensible, and provide users with an easy way of adding BGP community-set names to the list of reserved words.

We can play with a variety of tools to extract all community-set (or maybe just all named structures) as a first pass; maybe grep, maybe Batfish, maybe something in Netconan or bundled with it; maybe others.

**Comment by sfraint** [comment]
This behavior can now be accomplished using user-specified reserved words (#76 ).

For this example, running `Netconan` with `-p -r LOCAL-LASTRESORT,LOCAL-NOPREPEND,LOCAL-HIGHLOCPREF` will result in the output being:
```
community-set LOCAL-NOPREPEND
  1111:2222
end-set
!
community-set LOCAL-LASTRESORT
  1111:4444
end-set
!
community-set LOCAL-HIGHLOCPREF
  1111:1111
end-set
!
!
route-policy FOO
  if destination in BAR or destination in BAZ then
    set community LOCAL-NOPREPEND
    if destination in FOOBAR then
      set community LOCAL-LASTRESORT
    endif
    if destination in BAZBAR then
      set community LOCAL-HIGHLOCPREF
      set community LOCAL-LASTRESORT
    else
      set community LOCAL-NOPREPEND
      set community LOCAL-LASTRESORT
    endif
  else
    drop
  endif
end-policy
```
